name: CI - TEST CODE

on:
  push:
    branches:
        - develop
        - 'feature/**'
  pull_request:
    branches:
        - develop

jobs:
  test_and_lint:
    name: Run RSpec and Linters
    runs-on: ubuntu-latest
    env:
      RAILS_ENV: test
    steps:
        - name: Revisión de código
          uses: actions/checkout@v3

        - name: Set up Ruby
          uses: ruby/setup-ruby@v1
          with:
            ruby-version: '3.4.5' # ¡IMPORTANTE! Usa la misma versión de Ruby que tu proyecto.
            bundler-cache: true

        - name: Set up test database
          run: |
            bin/rails db:create
            bin/rails db:schema:load

        - name: Run RuboCop Linter
          run: bundle exec rubocop  

        - name: Run RSpec tests
          run: bundle exec rspec



